apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      containers:
      - name: streamlit-ui
        image: tejaswath/build_something:streamlit-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui
spec:
  type: NodePort
  selector:
    app: streamlit-ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30003